name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check flake
      run: nix flake check --print-build-logs

    - name: Run tests
      run: nix develop --command busted --verbose --coverage

    - name: Run linting
      run: nix develop --command luacheck lua/ --globals vim

    - name: Check formatting
      run: |
        nix develop --command stylua --check .
        if [ $? -ne 0 ]; then
          echo "Code formatting issues found. Run 'stylua .' to fix."
          exit 1
        fi

    - name: Generate coverage report
      run: nix develop --command luacov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./luacov.report.out
        fail_ci_if_error: false
        verbose: true

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build package
      run: nix build --print-build-logs

    - name: Verify package structure
      run: |
        ls -la result/
        find result/ -name "*.lua" | head -10